### ISSUE TITLE
File opening is unsuccessful

### ISSUE THREAD

**Issue by jleung51** [CtrlShiftGo/utilities#3]
On line 97, is_open() reports as false.

**Comment by CtrlShiftGo** [comment]
Fixed by switching to std::ios::in/out

http://stackoverflow.com/questions/28307047/what-is-the-difference-between-stdifstreamin-and-stdiosin-obviously-as

**Comment by jleung51** [comment]
Still not fixed for me:

> Attempting to open: "2016-02-28 Journal.md"
> 2016-02-28 Journal.md not found, attemping to make 2016-02-28 Journal.md

I have a solution though!

**Comment by jleung51** [comment]
[Issue fixed.](https://github.com/CtrlShiftGo/utilities/commit/174f0652033d9f7c55a44a3a467713ddcae0c8c9)
